#!/bin/bash

if [ $# -ne 2 ] ; then
 echo
 echo "Usage: `basename $0` <rdump file> <ophans file>"
 echo
 exit 1
fi

./nfsreplay --trace $1 --orphans $2  --server 10.0.17.4 /srv/nfs/10GBfolders/ --rsize 1048576 --wsize 1048576
