#!/bin/bash

if [ $# -ne 3 ] ; then
 echo
 echo "Usage: `basename $0` <rdump file> <ophans file> <anon file>"
 echo
 exit 1
fi

./td --stats --rdump $1 --fscreate /srv/nfs/10GBfolders $2 --trace $3 --blksize 102400 --wsize 1048576000
