#!/bin/bash

if [ $# -ne 1 ] ; then
 echo
 echo "Usage: `basename $0` <tcpdump file>"
 echo
 exit 1
fi

cd wireshark
export LD_LIBRARY_PATH=/usr/lib64:./wiretap/.libs/:./epan/.libs/ ; ./tshark -r $1 -o "tcp.desegment_tcp_streams:TRUE" -o "rpc.defragment_rpc_over_tcp:TRUE" -o "rpc.desegment_rpc_over_tcp:TRUE" -o "tcp.check_checksum:FALSE" -o "nfs.anon_dump_file:$1.anon" -o "nfs.disable_filepath_anon:TRUE" > /dev/null
